"""r3_raps_fidelity.py — Task 15 (PLAN_redesign_R3): 96^2-vs-512^2 RAPS band fidelity,
the measurement that may move `n` (`docs/REDESIGN_rngrn.md` §4.3).

THE GAP §4.3 NAMES. Training compares a 96^2 MODEL spectrum (solved on the commensurate
box `solve_box.geometry`, L_solve = p*2*pi/k_hat, p=8, n=96) to a 512^2 OBSERVED spectrum,
with "the model-side estimator's fidelity UNMEASURED at this grid": D2 measured band-limited
agreement with 512^2 at 256^2, not at 96^2 (`docs/DIAGNOSTICS_fft.md` D2). This script
measures that gap as a band-shape DISTANCE (not just D2's one-bin k* pass/fail), comparable
to D3's ~31%/bin estimation floor.

WHAT IS HELD FIXED, WHAT VARIES. The role of "the observed 512^2 frame" is played by the
SAME fixture checkpoint's own 512^2 rollout on the IDENTICAL commensurate box (same L, same
dynamics, and — in the paired sweep, which is the headline — the same physical initial
condition) as the 96^2 (and 128^2, 256^2) rollouts being tested. This isolates the
MODEL-SIDE ESTIMATOR's fidelity in isolation from the cross-domain gap: does representing
one pattern at n=96 (12 px/wavelength) reproduce the RAPS band shape a finely resolved n=512
representation of the SAME box shows? That is exactly the quantity §4.3 flags as unmeasured.
The SEPARATE cross-domain gap — interpolating a real dataset's 512^2 OBSERVED frame (a much
larger physical box, unrelated grid) onto the solve box — is Task 11's job, already measured
(`experiments/redesign_r3/solve_box_interp/results/interp_error.json`) and folded into this
report's summary per §4.3's explicit pairing instruction ("measured once per re-tile
geometry at R3, alongside the FD check").

NO payload.h5 IS OPENED — same reasoning as `scripts/diag_fft_d2.py`, whose fixture and
rollout apparatus this reuses directly (`load_fixture`, `linear_kstar`): every fixture is a
tracked RECOVERED checkpoint (a recovery OUTPUT, not the generator or the answer key). No
`tests/test_firewall.py::FORBIDDEN` entry is therefore needed.

WHY THE PAIRED SWEEP IS THE HEADLINE (`--paired`, fix round 1). `eval.rollout.simulate`
draws its IC as `x* + noise * default_rng(seed).standard_normal((N, n, n))` — a draw whose
SHAPE depends on n, so seed-s@96 and seed-s@512 are unrelated realisations that share
nothing physical. A distance between their saturated rollouts therefore conflates two
different quantities: the grid's fidelity, and the nonlinear selection of WHICH pattern each
independent solve settles into. The paired sweep separates them. Per (fixture, seed) it
draws ONE 512^2 initial condition exactly as `simulate` would (`paired_initial_field`;
reproduction verified per seed against the committed unpaired row — same k*, same step
count, `_verify_against_committed`), spectrally decimates it per species to each coarse n
(`decimate_ic`), and rolls every grid out from its own band-limited copy of that SAME
physical field. Grid fidelity is then the only thing that differs between the arms, and the
paired numbers are the grid-fidelity answer §4.3 asked for.

The ORIGINAL unpaired sweep (`--tag` with no `--paired`, `raps_fidelity.json`) is RETAINED
and REFRAMED, not withdrawn: it is a real measurement of the other quantity — how much the
saturated band shape moves between independent nonlinear solves of the same model on the
same box. Read it as pattern-selection variance, never as grid fidelity.

Passing an explicit IC needed one additive change in the package: `eval.rollout.simulate`
gained an optional `X0=None` parameter whose default reproduces the previous behaviour
exactly (same draw, same `seed`/`noise`/`xstar` semantics). Nothing else in `src/rngrn/`
was touched by this measurement branch.

FIXTURE SELECTION IS A TRACKED ARTIFACT, not a docstring claim:
`results/fixture_enumeration.json`, generated by `--enumerate-fixtures`, lists all 11
tracked `checkpoints/model.pt` with each one's `steady_state` convergence, dispersion-scan
argmax, `linear_kstar` verdict and (where defined) `k_lin`/`sig_max_lin`, plus the
near-duplicate pairs and which candidates `FIXTURES` selected. Measured: 5 of 11 are
Turing-unstable (the other 6 have their dispersion argmax pinned at the k-grid floor with
sig_max < 0 — D5's own finding), and those 5 fall into just TWO k_lin clusters at a 1%
tolerance — `tune_comp_seed3` at 0.1749 alone, and all four D5 ones inside 0.35% of each
other at ~0.283. `FIXTURES` takes two fixtures (`d5_seed3`, `d5_seed5`) from that single
cluster; they differ materially in `sig_max_lin` (0.964 vs 0.824) and in time-to-saturation,
so they are not redundant models, but the selection does NOT sample three distinct k_lin.
An earlier version of this docstring said one near-duplicate was dropped "in favour of the
more different pair" — the enumeration shows that is not what the k_lin numbers say, and
the artifact is the record.

BAND BIN COUNT IS AN n-INVARIANT. The solve box's RAPS bin width is dk = 2*pi/L_solve =
k_lin/p, a function of p ALONE — so B_train holds the same 7 bins at n=96 as at n=512
(`n_band_bins_by_grid` in the aggregated artifacts reads `[7]` at every grid). Raising n
cannot buy band RESOLUTION; only raising p can. This is the single most decision-relevant
fact for the owner's n-question, and it is a property of the geometry, not of this data.

METHOD, per (fixture, grid, seed) — shared by both sweeps, which differ ONLY in step 2's
initial condition (paired: the decimated 512^2 IC; unpaired: `simulate`'s own per-n draw):
  1. `diag_fft_d2.load_fixture` + `linear_kstar` → the fixture model and its own dispersion
     argmax k_lin. L = p*2*pi/k_lin (p=8, `solve_box.P_DEFAULT`), fixed across every grid
     for that fixture.
  2. `eval.rollout.simulate` at n in {96, 128, 256, 512}, `early_stop=True`, same L.
     NOTE (re-review finding): early_stop is a RULE, not a guarantee — d5_seed3/d5_seed5
     arms stop saturated, but every tune_comp_seed3 arm (all 64) runs to the planned
     horizon (`stopped_reason: "horizon"`, 606 steps), i.e. that fixture's fields are
     late-growth, not detected-saturated. Both arms of a pair hit the SAME horizon, and
     the shape-normalised distance cancels uniform amplitude, so the residual bias from
     the coarse IC's smaller noise amplitude is conservative (inflates the coarse arm's
     distance; cannot manufacture a pass). The n=512 solve is REQUIRED per seed regardless
     of grid count — it is the reference every other grid is compared against, not merely
     "a grid being tested" — so it cannot be skipped; what IS skipped is treating it as
     an open question (n=512-vs-itself is CHECKED to be ~0 every time, cheaply, and raises
     if it is not, rather than being re-derived).
  3. `observables.raps` (register item 15's UNWINDOWED primary estimator; the Hann-Welch
     path stays report-only under item 15's ratified both-sides-identical rule) of each
     field. `k_lin` (the fixture's own dispersion argmax, the same k that fixed L in step
     1) plays "k*_obs" here — B_train = [0.60, 1.55]*k*_obs, D-FFT-9 closure 1 — since
     this self-consistency test has no independent "observed" domain (see caveat below);
     each seed's OWN nonlinearly-realised k* is reported separately (drifts a few % from
     k_lin — a real, secondary finding, not folded into the distance metric).
  4. `solve_box.geometry(k_lin)` — the SAME (p=8) box a real training step would build at
     the idealised post-ignition operating point (k_hat == k*_obs); using k_lin keeps
     `L_solve` equal to the field's real L exactly, so the box's bin array aligns
     index-for-index with `observables.raps(field_model, L)`'s own array. `solve_box.
     band_bins` selects its B_train bins (bin WIDTH dk = k_lin/p depends only on p, not
     n, so the band's bin COUNT is identical across every grid tested — Task 11's
     `n_band_bins=7` for this p, reproduced). Two earlier, WRONG forms of this script used
     the per-seed measured k* for the box geometry (misaligns the bin array with L) or as
     `interpolate_targets`'s `kstar_obs` while the box used k_lin (reads the k_lin-vs-
     measured-k* drift as spurious distance) — both caught by the sanity check that n=512
     compared against itself must give ~0 distance; see `raps_band_distance`'s docstring.
  5. `solve_box.interpolate_targets` — the 512^2 RAPS's log-power, sampled on the FINE
     grid, interpolated onto the box's scale-free band-bin positions: the ACTUAL target
     construction the R3 forward-solve geometry performs (dogfooded, not reimplemented).
  6. spec_shape-form distance (`docs/SPEC_fourier_training.md` §5): both sides normalised
     by their OWN B_train sum, sum of squared log-ratio differences over the band bins;
     converted to a "%/bin" figure via `sqrt(distance / n_bins) * 100`, the SAME conversion
     D3 used to turn its 0.389 mean distance into "~31% per-bin power variation"
     (`docs/DIAGNOSTICS_fft.md` D3; reproduced from `experiments/diag_fft/d3/results.json`:
     sqrt(0.38854 / 4) * 100 = 31.17, matching "≈ 31%").

A SUPPLEMENTARY CONTROL, AND WHY IT TURNED OUT DEGENERATE. An independent ETDRK4 rollout at
each n (step 2) is not just a coarser VIEW of one field — it is a separate nonlinear
integration that can settle into a different realised mode/phase from the same seed, so a
first concern was that the rollout-based distance might be measuring pattern-selection
variance rather than grid fidelity. `decimate_field` was added to check this: it
ideal-band-limit-downsamples the SAME converged 512^2 field to each coarser n (no re-solve)
and measures the same distance. It reads EXACTLY 0.00% at every n and seed — and this is
DEGENERATE, not a cleaner measurement: an ideal Fourier truncation is lossless for any
content strictly inside the kept band, and B_train's highest bin sits far below every tested
grid's Nyquist — so the control CANNOT show a nonzero distance by construction, whatever the
true grid-fidelity gap is. What it DOES confirm is that the rollout-based distances are a
genuine effect of solving at n=96 (etc.), not an artifact of this script's resampling
arithmetic. It is reported as that confirmatory control, never as an n-verdict.

What it could NOT do is settle the confound it was added to probe — that needed the paired
sweep above, which resolves it properly: same physical IC, band-limited, re-solved at each
grid. The decimation operator survives into the paired sweep as `decimate_ic`, now doing
real work (building the coarse ICs) rather than only controlling.

Usage (CLAUDE.md §7c: no discretised Laplacian; this is CPU, no GPU, no guard needed — it is
not a trainer; pin OMP_NUM_THREADS=1 per fixture and run fixtures in separate PROCESSES for
parallelism, not threads. One fixture per process, three in parallel):
    .venv/bin/python -u scripts/r3_raps_fidelity.py --enumerate-fixtures
    KMP_AFFINITY=disabled OMP_NUM_THREADS=1 .venv/bin/python -u scripts/r3_raps_fidelity.py \\
        --paired --tag tune_comp_seed3 --seeds 0,1,2,3,4,5,6,7      # HEADLINE
    ... (repeat per fixture in FIXTURES, in parallel processes) ...
    .venv/bin/python -u scripts/r3_raps_fidelity.py --aggregate-paired
    # the retained unpaired (pattern-selection-variance) sweep, same shape without --paired:
    KMP_AFFINITY=disabled OMP_NUM_THREADS=1 .venv/bin/python -u scripts/r3_raps_fidelity.py \\
        --tag tune_comp_seed3 --seeds 0,1,2,3,4,5,6,7
    .venv/bin/python -u scripts/r3_raps_fidelity.py --aggregate

Writes, under experiments/redesign_r3/raps_fidelity/results/:
    fixture_enumeration.json       every tracked checkpoint, its Turing verdict, selection
    raps_fidelity_paired_<tag>.json / raps_fidelity_paired.json    PAIRED — grid fidelity
    raps_fidelity_<tag>.json       / raps_fidelity.json            UNPAIRED — pattern
                                                                   selection variance
Deterministic given the tracked fixture checkpoints and the given seeds.
"""
from __future__ import annotations

import argparse
import glob
import json
import os
import resource
import sys
import time

import numpy as np
import torch

torch.set_default_dtype(torch.float64)
torch.set_num_threads(1)

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "src"))
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from rngrn import observables as obs                              # noqa: E402
from rngrn import solve_box as sb                                 # noqa: E402
from rngrn.eval.rollout import simulate                            # noqa: E402
from diag_fft_d2 import load_fixture, linear_kstar                 # noqa: E402

GRIDS = (96, 128, 256, 512)          # 512 is the reference; ascending for an honest RSS read
CHECK_EVERY = 200
P = sb.P_DEFAULT                     # 8 — D-FFT-9/D1 commensurate periods
B_LO, B_HI = 0.60, 1.55              # D-FFT-9 closure 1

OUT_DIR = os.path.join("experiments", "redesign_r3", "raps_fidelity", "results")

#: Every Turing-unstable TRACKED checkpoint in this repo (see module docstring for how this
#: was enumerated). tag -> checkpoint path.
FIXTURES = {
    "tune_comp_seed3": "experiments/tune_comp/runs/m3_registry_20260803_190250_seed3/"
                       "checkpoints/model.pt",
    "d5_seed3": "experiments/diag_fft/d5/runs/m3_registry_20260812_092043_seed3/"
               "checkpoints/model.pt",
    "d5_seed5": "experiments/diag_fft/d5/runs/m3_registry_20260812_092043_seed5/"
               "checkpoints/model.pt",
}

#: D3's ~31%/bin RAPS estimation floor (docs/DIAGNOSTICS_fft.md D3), reproduced from the
#: tracked experiments/diag_fft/d3/results.json (not re-derived here — quoted, as
#: measure_interp_error.py also quotes it for the same purpose).
D3_FLOOR_PCT = 31.0

#: Task 11's target-interpolation error (docs/REDESIGN_rngrn.md §4.3's paired measurement),
#: folded into this report per Step 4.
TASK11_INTERP_JSON = os.path.join(
    "experiments", "redesign_r3", "solve_box_interp", "results", "interp_error.json")


def _j(x):
    if isinstance(x, (np.floating, np.integer)):
        x = x.item()
    if isinstance(x, float) and not np.isfinite(x):
        return None
    return x


def _rss_kib() -> int:
    return resource.getrusage(resource.RUSAGE_SELF).ru_maxrss


def _pcts_or_raise(grid_rows: list[dict], where: str) -> list[float]:
    """Every row's `per_bin_pct`, or raise. `_j` maps a non-finite distance to None, and
    silently dropping those (an earlier `if ... is not None` filter here did) would shrink
    the sample behind a mean/max/verdict without saying so — the sample size would no
    longer be the seed count. A non-finite distance is a defect, not a value (CLAUDE.md
    §4, `.claude/rules/reporting-numbers.md`)."""
    bad = [row.get("seed") for row in grid_rows if row["per_bin_pct"] is None]
    if bad:
        raise RuntimeError(
            f"[{where}] non-finite per-bin distance for seed(s) {bad} — a NaN/inf distance "
            "is a defect, not a value; refusing to summarise over a silently shrunk sample")
    return [float(row["per_bin_pct"]) for row in grid_rows]


# --------------------------------------------------------------------------- measurement

def raps_band_distance(field_model: np.ndarray, ref_log_power: np.ndarray,
                       ref_k_centers: np.ndarray, k_hat: float, L: float) -> dict:
    """spec_shape-form log-RAPS band distance between `field_model`'s OWN RAPS (its grid's
    n implied by field_model.shape) and the 512^2 reference RAPS, interpolated onto the
    model's solve-box band-bin positions via `solve_box.interpolate_targets` — SPEC §5,
    exactly as a real training step would build the target at this operating point.

    `k_hat` plays BOTH roles a real training step keeps formally separate: the box's own
    commensurability driver (`L = p*2*pi/k_hat` — box geometry MUST use this value, not a
    per-seed measured k*, or `geometry(...)["L_solve"]` stops equalling the field's actual
    physical L and the box's bin array silently misaligns index-for-index with
    `observables.raps(field_model, L)`'s own array — a real bug this script had, caught by
    the sanity check that n=512 compared against itself must give ~0 distance), AND the
    `kstar_obs` `interpolate_targets` normalises against. §4.3's actual training design
    keeps these SEPARATE (k_hat drifts from the true k*_obs between re-tiles, bounded by
    the re-tile hysteresis |Delta k_hat|/k_hat > 1/(2p)) — but there is no independent
    "observed" domain in this self-consistency test (the fixture provides only itself), so
    k_hat plays k*_obs exactly, the idealised post-ignition operating point the hysteresis
    is designed to hold the real run near. Passing the SEED's own measured k* (which drifts
    a few % from k_hat here via nonlinear finite-size mode selection, reported separately)
    as `kstar_obs` instead would make even n=512-vs-itself read that drift as spurious
    "distance" — the second form this script's bug took before both roles were pinned to
    the same k_hat.
    """
    box = sb.geometry(k_hat, p=P, n=field_model.shape[-1])
    band_idx = sb.band_bins(box, B_LO, B_HI)

    k_mod, p_mod, _ = obs.raps(field_model, L)
    model_band_power = p_mod[band_idx]
    if (model_band_power <= 0).any():
        raise RuntimeError(
            f"non-positive model RAPS power inside the band at n={field_model.shape[-1]} — "
            "log-shape distance undefined")

    target_log = sb.interpolate_targets(ref_log_power, ref_k_centers, k_hat,
                                        box, B_LO, B_HI).numpy()
    target_power = np.exp(target_log)

    s_model = model_band_power / model_band_power.sum()
    s_target = target_power / target_power.sum()
    distance = float(np.sum((np.log(s_model) - np.log(s_target)) ** 2))
    n_bins = int(len(band_idx))
    per_bin_pct = float(np.sqrt(distance / n_bins) * 100.0)
    return dict(n_band_bins=n_bins, distance=distance, per_bin_pct=per_bin_pct,
                L_solve=box["L_solve"])


def decimate_field(field: np.ndarray, n_target: int) -> np.ndarray:
    """Ideal band-limited downsample of a periodic `field` to `n_target x n_target`, on the
    SAME physical L (Fourier-truncate to the central `n_target x n_target` frequency block,
    inverse transform). This is the textbook alias-free decimation operator for a periodic
    signal — the low-frequency content a coarser FFT-basis grid resolves of the SAME field,
    with no independent PDE re-solve. Used as a supplementary, degenerate-but-confirmatory
    control — see the module docstring's "SUPPLEMENTARY CONTROL" paragraph.
    """
    n_src = field.shape[-1]
    if n_target > n_src:
        raise ValueError(f"cannot decimate to a FINER grid ({n_target} > {n_src})")
    F = np.fft.fftshift(np.fft.fft2(field))
    c = n_src // 2
    h = n_target // 2
    Ft = F[c - h:c + h, c - h:c + h]
    down = np.fft.ifft2(np.fft.ifftshift(Ft)) * (n_target * n_target) / (n_src * n_src)
    return np.real(down)


def rollout_and_raps(model, L: float, n: int, seed: int, X0: np.ndarray | None = None) -> dict:
    """One ETDRK4 rollout to saturation plus its RAPS. `X0=None` keeps `simulate`'s own
    drawn IC (the UNPAIRED sweep); an explicit `X0` is the PAIRED sweep's decimated copy of
    the 512^2 IC — see `run_fixture_paired`."""
    rss_before = _rss_kib()
    t0 = time.perf_counter()
    r = simulate(model, L, n=n, seed=seed, integrator="etdrk4_rfft",
                early_stop=True, check_every=CHECK_EVERY, X0=X0)
    seconds = time.perf_counter() - t0
    rss_after = _rss_kib()
    if r["blew_up"]:
        raise RuntimeError(f"rollout blew up at n={n}, seed={seed} — no field to measure")
    field0 = np.asarray(r["fields"])[0]
    k_c, power, kstar = obs.raps(field0, L)
    nonzero = power > 0.0
    return dict(n=n, seed=seed, field0=field0, k_centers=k_c[nonzero],
                log_power=np.log(power[nonzero]), kstar=float(kstar),
                stopped_reason=r["stopped_reason"], patterned=bool(r["patterned"]),
                seconds=seconds, nsteps_run=int(r["nsteps_run"]),
                rss_before_kib=rss_before, rss_after_kib=rss_after,
                sec_per_step=seconds / max(1, int(r["nsteps_run"])))


# --------------------------------------------------------------------------- per-fixture

def run_fixture(ckpt_path: str, tag: str, seeds: tuple[int, ...]) -> dict:
    model = load_fixture(ckpt_path)
    k_lin, sig_max_lin, xstar = linear_kstar(model)
    L = P * 2.0 * np.pi / k_lin
    print(f"[{tag}] fixture: {ckpt_path}")
    print(f"[{tag}]   k*_lin={k_lin:.6f}, sig_max={sig_max_lin:.6f}, L={L:.4f} "
          f"({P} periods/box), seeds={list(seeds)}")

    rows = []
    ref_by_seed: dict[int, dict] = {}
    for seed in seeds:
        r512 = rollout_and_raps(model, L, 512, seed)
        ref_by_seed[seed] = r512
        rows.append(r512)
        print(f"[{tag}]   seed {seed}: n=512 kstar={r512['kstar']:.6f} "
              f"stopped={r512['stopped_reason']} patterned={r512['patterned']} "
              f"{r512['seconds']:.2f}s / {r512['nsteps_run']} steps")

    results_by_grid: dict[str, dict] = {}
    for n in GRIDS:
        grid_rows = []
        for seed in seeds:
            if n == 512:
                r = ref_by_seed[seed]
            else:
                r = rollout_and_raps(model, L, n, seed)
                rows.append(r)
            ref = ref_by_seed[seed]
            dist = raps_band_distance(r["field0"], ref["log_power"], ref["k_centers"],
                                      k_lin, L)
            if n == 512:
                # Sanity check (caught real bugs during development, kept as a live
                # assertion): comparing the n=512 reference against itself must give ~0
                # distance — a nonzero value here means the box/array alignment is wrong
                # again, not a genuine grid-fidelity finding. Cheap; run every time.
                # RuntimeError, not `assert`: this check is load-bearing and must survive
                # `python -O`, like every other check in this file.
                if not dist["per_bin_pct"] < 1.0:
                    raise RuntimeError(
                        f"[{tag}] n=512 vs itself gave {dist['per_bin_pct']:.2f}%/bin, not "
                        "~0 — box geometry is misaligned with the model-side RAPS array")
            dk_bin = 2.0 * np.pi / L
            grid_rows.append(dict(
                seed=seed, kstar=_j(r["kstar"]), kstar_512=_j(ref["kstar"]),
                dk_kstar=_j(abs(r["kstar"] - ref["kstar"])),
                within_one_bin=bool(abs(r["kstar"] - ref["kstar"]) <= dk_bin),
                stopped_reason=r["stopped_reason"], patterned=r["patterned"],
                seconds=_j(r["seconds"]), nsteps_run=r["nsteps_run"],
                sec_per_step=_j(r["sec_per_step"]),
                n_band_bins=dist["n_band_bins"], distance=_j(dist["distance"]),
                per_bin_pct=_j(dist["per_bin_pct"]),
            ))
            print(f"[{tag}]   n={n:4d} seed={seed}: per_bin_pct={dist['per_bin_pct']:6.2f}%  "
                  f"(distance={dist['distance']:.4f}, {dist['n_band_bins']} bins)  "
                  f"{r['seconds']:.3f}s/{r['nsteps_run']}steps")
        pcts = _pcts_or_raise(grid_rows, f"{tag} n={n}")
        secs = [row["seconds"] for row in grid_rows]
        steps = [row["nsteps_run"] for row in grid_rows]
        clears_floor = bool(max(pcts) < D3_FLOOR_PCT)
        results_by_grid[str(n)] = dict(
            n=n, rows=grid_rows,
            per_bin_pct_mean=float(np.mean(pcts)),
            per_bin_pct_max=float(np.max(pcts)),
            per_bin_pct_min=float(np.min(pcts)),
            clears_d3_floor_all_seeds=clears_floor,
            seconds_mean=float(np.mean(secs)), seconds_min=float(np.min(secs)),
            seconds_max=float(np.max(secs)),
            steps_mean=float(np.mean(steps)),
        )

    # ---- supplementary, degenerate-but-confirmatory control: decimate the SAME converged
    # 512^2 field to each coarser n (no independent re-solve) — see module docstring.
    decimated_by_grid: dict[str, dict] = {}
    for n in GRIDS:
        if n == 512:
            continue
        grid_rows = []
        for seed in seeds:
            ref = ref_by_seed[seed]
            field_dec = decimate_field(ref["field0"], n)
            dist = raps_band_distance(field_dec, ref["log_power"], ref["k_centers"],
                                      k_lin, L)
            grid_rows.append(dict(seed=seed, n_band_bins=dist["n_band_bins"],
                                  distance=_j(dist["distance"]),
                                  per_bin_pct=_j(dist["per_bin_pct"])))
        pcts = _pcts_or_raise(grid_rows, f"{tag} decimated n={n}")
        decimated_by_grid[str(n)] = dict(
            n=n, rows=grid_rows,
            per_bin_pct_mean=float(np.mean(pcts)), per_bin_pct_max=float(np.max(pcts)),
            per_bin_pct_min=float(np.min(pcts)),
            clears_d3_floor_all_seeds=bool(max(pcts) < D3_FLOOR_PCT))
        dg = decimated_by_grid[str(n)]
        print(f"[{tag}]   [decimated] n={n:4d}: mean={dg['per_bin_pct_mean']:.2e}% "
              f"max={dg['per_bin_pct_max']:.2e}%")
    decimated_by_grid["512"] = dict(n=512, rows=[], per_bin_pct_mean=0.0,
                                    per_bin_pct_max=0.0, per_bin_pct_min=0.0,
                                    clears_d3_floor_all_seeds=True)

    peak_rss_kib = max(_rss_kib(), *(r["rss_after_kib"] for r in rows))

    n_verdict = None
    for n in GRIDS:
        if results_by_grid[str(n)]["clears_d3_floor_all_seeds"]:
            n_verdict = n
            break

    summary = dict(
        tag=tag, fixture=ckpt_path, k_lin=_j(k_lin), sig_max_lin=_j(sig_max_lin), L=_j(L),
        p=P, band=[B_LO, B_HI], seeds=list(seeds), grids=list(GRIDS),
        d3_estimation_floor_pct=D3_FLOOR_PCT,
        per_grid={n: dict(per_bin_pct_mean=results_by_grid[str(n)]["per_bin_pct_mean"],
                          per_bin_pct_max=results_by_grid[str(n)]["per_bin_pct_max"],
                          clears_d3_floor_all_seeds=
                              results_by_grid[str(n)]["clears_d3_floor_all_seeds"],
                          seconds_mean=results_by_grid[str(n)]["seconds_mean"],
                          decimated_per_bin_pct_mean=
                              decimated_by_grid[str(n)]["per_bin_pct_mean"],
                          decimated_per_bin_pct_max=
                              decimated_by_grid[str(n)]["per_bin_pct_max"])
                  for n in GRIDS},
        coarsest_grid_clearing_floor=n_verdict,
        peak_rss_kib=peak_rss_kib,
    )

    out_path = os.path.join(OUT_DIR, f"raps_fidelity_{tag}.json")
    os.makedirs(OUT_DIR, exist_ok=True)
    with open(out_path, "w") as fh:
        json.dump(dict(summary=summary, by_grid=results_by_grid,
                       decimated_by_grid=decimated_by_grid), fh, indent=2)

    print(f"[{tag}] D3 floor: ~{D3_FLOOR_PCT:.0f}%/bin")
    for n in GRIDS:
        g = results_by_grid[str(n)]
        verdict = "CLEARS" if g["clears_d3_floor_all_seeds"] else "FAILS"
        print(f"[{tag}]   n={n:4d}: mean={g['per_bin_pct_mean']:6.2f}% "
              f"max={g['per_bin_pct_max']:6.2f}% -> {verdict}  "
              f"(mean {g['seconds_mean']:.2f}s/rollout, {len(seeds)} seeds)")
    print(f"[{tag}] coarsest grid clearing the floor: {n_verdict}")
    print(f"[{tag}] peak RSS: {peak_rss_kib / 1024:.1f} MiB")
    print(f"[{tag}] wrote {out_path}")
    return summary


# ---------------------------------------------------------------- PAIRED (the headline)

#: `eval.rollout.simulate`'s own default IC noise amplitude, restated here because the
#: paired IC is reconstructed by reproducing that function's exact draw. If the two ever
#: drift apart, `_verify_against_committed` fails on the first seed — that check, not this
#: comment, is what holds them together.
ROLLOUT_NOISE = 1e-2


def paired_initial_field(xstar: np.ndarray, n_ref: int, seed: int) -> np.ndarray:
    """Reproduce, bit-for-bit, the (N, n_ref, n_ref) initial field `eval.rollout.simulate`
    draws for this `seed` — `x* + noise * default_rng(seed).standard_normal((N, n, n))`,
    the ONLY consumer of that generator in the function, so the call sequence is a single
    draw and the field is reproducible exactly.

    Verified per (fixture, seed) by `run_fixture_paired`: the n=512 rollout started from
    this field is required to reproduce the committed unpaired run's row (same k*, same
    step count) — see `_verify_against_committed`.
    """
    rng = np.random.default_rng(seed)
    N = int(xstar.shape[0])
    return xstar[:, None, None] + ROLLOUT_NOISE * rng.standard_normal((N, n_ref, n_ref))


def decimate_ic(X0: np.ndarray, n_target: int) -> np.ndarray:
    """`decimate_field` applied PER SPECIES to an (N, n, n) initial field.

    Species-wise because `decimate_field` fftshifts every axis it is given, which is right
    for a 2-D field and wrong for a stack (it would roll the species axis). The result is
    the band-limited part of the SAME physical initial condition — the most of it the
    coarse grid can represent.

    NOTE, disclosed rather than corrected: ideal decimation keeps only (n_target/n_ref)^2 of
    the modes, so the coarse IC's noise STD is smaller by n_target/n_ref (0.19x at 96 from
    512). That is not a defect of the pairing — it is the physical statement that the coarse
    grid cannot carry the high-k half of the same noise field. It costs a slightly longer
    induction (ln(512/96)/sig_max ~ 1.7/sig_max, i.e. ~4% of the 40-growth-time horizon),
    recorded per run as `nsteps_run`/`stopped_reason`. Rescaling the amplitude back up would
    break the pairing outright by changing the low-k content the fine run also sees.
    """
    return np.stack([decimate_field(X0[i], n_target) for i in range(X0.shape[0])])


def _committed_row(tag: str, n: int, seed: int) -> dict | None:
    """The matching row from the COMMITTED unpaired artifact, for the reproduction check.
    None when the unpaired artifact is absent (a first-ever paired run)."""
    path = os.path.join(OUT_DIR, f"raps_fidelity_{tag}.json")
    if not os.path.exists(path):
        return None
    with open(path) as fh:
        doc = json.load(fh)
    for row in doc["by_grid"][str(n)]["rows"]:
        if row["seed"] == seed:
            return row
    return None


def _verify_against_committed(tag: str, seed: int, r512: dict) -> dict:
    """The n=512 arm of the paired run IS the unpaired run — same seed, same IC, same
    dynamics — so it must reproduce the committed row. This is the check that the IC
    reconstruction in `paired_initial_field` is exact rather than merely similar.

    Fails loud on a mismatch: if the reconstruction were wrong, every paired distance below
    would be measured against a reference that is not the one the committed table reports.
    """
    ref = _committed_row(tag, 512, seed)
    if ref is None:
        return dict(checked=False, reason="no committed unpaired artifact to compare to")
    dk = abs(r512["kstar"] - ref["kstar"])
    if dk > 1e-9 or int(r512["nsteps_run"]) != int(ref["nsteps_run"]):
        raise RuntimeError(
            f"[{tag}] seed {seed}: the reconstructed 512^2 IC does NOT reproduce the "
            f"committed unpaired run — k*={r512['kstar']!r} vs {ref['kstar']!r} "
            f"(|d|={dk:.3g}), steps={r512['nsteps_run']} vs {ref['nsteps_run']}. The "
            "paired references would not be the committed ones; refusing to report.")
    return dict(checked=True, dk_star=_j(dk), nsteps_run=int(r512["nsteps_run"]),
                committed_nsteps_run=int(ref["nsteps_run"]))


def run_fixture_paired(ckpt_path: str, tag: str, seeds: tuple[int, ...]) -> dict:
    """PAIRED grid-fidelity sweep — the headline measurement (see the module docstring's
    "WHY THE PAIRED SWEEP IS THE HEADLINE").

    Per (fixture, seed): reconstruct the 512^2 IC exactly as `simulate` drew it, decimate it
    to each coarse n, roll every grid out from ITS OWN band-limited copy of that ONE physical
    initial condition, and compare each coarse RAPS band shape to the 512^2 one. Grid
    fidelity is then the only thing that differs between the arms.
    """
    model = load_fixture(ckpt_path)
    k_lin, sig_max_lin, xstar = linear_kstar(model)
    L = P * 2.0 * np.pi / k_lin
    print(f"[{tag}] PAIRED fixture: {ckpt_path}")
    print(f"[{tag}]   k*_lin={k_lin:.6f}, sig_max={sig_max_lin:.6f}, L={L:.4f} "
          f"({P} periods/box), seeds={list(seeds)}")

    results_by_grid: dict[str, dict] = {str(n): dict(n=n, rows=[]) for n in GRIDS}
    verifications = []
    rss_rows = []
    for seed in seeds:
        X0_ref = paired_initial_field(xstar, 512, seed)
        # n=512 FIRST: it is the reference every coarse grid is scored against, and the
        # arm whose reproduction of the committed unpaired row proves the IC is exact.
        r512 = rollout_and_raps(model, L, 512, seed, X0=X0_ref)
        rss_rows.append(r512)
        ver = _verify_against_committed(tag, seed, r512)
        verifications.append(dict(seed=seed, **ver))
        print(f"[{tag}]   seed {seed}: n=512 kstar={r512['kstar']:.6f} "
              f"steps={r512['nsteps_run']} {r512['seconds']:.2f}s  reproduces_committed="
              f"{ver.get('checked')}")
        for n in GRIDS:
            if n == 512:
                r, ic_std = r512, float(X0_ref.std())
            else:
                X0_n = decimate_ic(X0_ref, n)
                ic_std = float(X0_n.std())
                r = rollout_and_raps(model, L, n, seed, X0=X0_n)
                rss_rows.append(r)
            dist = raps_band_distance(r["field0"], r512["log_power"], r512["k_centers"],
                                      k_lin, L)
            if n == 512 and not dist["per_bin_pct"] < 1.0:
                raise RuntimeError(
                    f"[{tag}] n=512 vs itself gave {dist['per_bin_pct']:.2f}%/bin, not ~0 "
                    "— box geometry is misaligned with the model-side RAPS array")
            dk_bin = 2.0 * np.pi / L
            results_by_grid[str(n)]["rows"].append(dict(
                seed=seed, kstar=_j(r["kstar"]), kstar_512=_j(r512["kstar"]),
                dk_kstar=_j(abs(r["kstar"] - r512["kstar"])),
                within_one_bin=bool(abs(r["kstar"] - r512["kstar"]) <= dk_bin),
                stopped_reason=r["stopped_reason"], patterned=r["patterned"],
                seconds=_j(r["seconds"]), nsteps_run=r["nsteps_run"],
                sec_per_step=_j(r["sec_per_step"]), ic_std=_j(ic_std),
                n_band_bins=dist["n_band_bins"], distance=_j(dist["distance"]),
                per_bin_pct=_j(dist["per_bin_pct"]),
            ))
            print(f"[{tag}]   n={n:4d} seed={seed}: per_bin_pct={dist['per_bin_pct']:6.2f}%  "
                  f"({dist['n_band_bins']} bins)  {r['seconds']:.3f}s/{r['nsteps_run']}steps "
                  f"stopped={r['stopped_reason']}")

    for n in GRIDS:
        g = results_by_grid[str(n)]
        pcts = _pcts_or_raise(g["rows"], f"{tag} paired n={n}")
        secs = [row["seconds"] for row in g["rows"]]
        g.update(per_bin_pct_mean=float(np.mean(pcts)), per_bin_pct_max=float(np.max(pcts)),
                 per_bin_pct_min=float(np.min(pcts)),
                 clears_d3_floor_all_seeds=bool(max(pcts) < D3_FLOOR_PCT),
                 seconds_mean=float(np.mean(secs)), seconds_min=float(np.min(secs)),
                 seconds_max=float(np.max(secs)),
                 steps_mean=float(np.mean([row["nsteps_run"] for row in g["rows"]])))

    n_verdict = next((n for n in GRIDS
                      if results_by_grid[str(n)]["clears_d3_floor_all_seeds"]), None)
    summary = dict(
        tag=tag, fixture=ckpt_path, paired=True, k_lin=_j(k_lin),
        sig_max_lin=_j(sig_max_lin), L=_j(L), p=P, band=[B_LO, B_HI], seeds=list(seeds),
        grids=list(GRIDS), d3_estimation_floor_pct=D3_FLOOR_PCT,
        ic_noise=ROLLOUT_NOISE, ic_reference_grid=512,
        per_grid={n: {k: results_by_grid[str(n)][k] for k in
                      ("per_bin_pct_mean", "per_bin_pct_max", "per_bin_pct_min",
                       "clears_d3_floor_all_seeds", "seconds_mean")} for n in GRIDS},
        coarsest_grid_clearing_floor=n_verdict,
        ic_reconstruction_check=verifications,
        peak_rss_kib=max(_rss_kib(), *(r["rss_after_kib"] for r in rss_rows)),
    )
    out_path = os.path.join(OUT_DIR, f"raps_fidelity_paired_{tag}.json")
    os.makedirs(OUT_DIR, exist_ok=True)
    with open(out_path, "w") as fh:
        json.dump(dict(summary=summary, by_grid=results_by_grid), fh, indent=2)

    print(f"[{tag}] PAIRED — D3 floor: ~{D3_FLOOR_PCT:.0f}%/bin")
    for n in GRIDS:
        g = results_by_grid[str(n)]
        verdict = "CLEARS" if g["clears_d3_floor_all_seeds"] else "FAILS"
        print(f"[{tag}]   n={n:4d}: mean={g['per_bin_pct_mean']:6.2f}% "
              f"max={g['per_bin_pct_max']:6.2f}% -> {verdict}")
    print(f"[{tag}] coarsest grid clearing the floor: {n_verdict}")
    print(f"[{tag}] wrote {out_path}")
    return summary


def aggregate_paired() -> int:
    """Merge every raps_fidelity_paired_<tag>.json into raps_fidelity_paired.json, and set
    each paired mean beside the UNPAIRED one from the same (fixture, grid) so the size of
    the confound the pairing removes is readable directly."""
    paths = sorted(glob.glob(os.path.join(OUT_DIR, "raps_fidelity_paired_*.json")))
    if not paths:
        raise RuntimeError(f"no paired per-fixture results under {OUT_DIR} — run with "
                           "--paired --tag <fixture> first")
    unpaired_path = os.path.join(OUT_DIR, "raps_fidelity.json")
    if not os.path.exists(unpaired_path):
        raise FileNotFoundError(
            f"{unpaired_path} not found — the paired report is stated AGAINST the unpaired "
            "sweep it reframes; run --aggregate first rather than reporting it alone")
    with open(unpaired_path) as fh:
        unpaired = json.load(fh)

    by_fixture = {}
    for p in paths:
        with open(p) as fh:
            d = json.load(fh)
        by_fixture[d["summary"]["tag"]] = d

    rows = []
    for tag, d in by_fixture.items():
        pg = d["summary"]["per_grid"]
        upg = unpaired["by_fixture"][tag]["per_grid"]
        for n in ("96", "128", "256"):
            rows.append(dict(
                tag=tag, n=int(n),
                paired_mean=pg[n]["per_bin_pct_mean"], paired_max=pg[n]["per_bin_pct_max"],
                paired_min=pg[n]["per_bin_pct_min"],
                unpaired_mean=upg[n]["per_bin_pct_mean"],
                unpaired_max=upg[n]["per_bin_pct_max"],
                paired_clears_floor_all_seeds=pg[n]["clears_d3_floor_all_seeds"],
                confound_removed_mean_pts=pg[n]["per_bin_pct_mean"]
                                          - upg[n]["per_bin_pct_mean"]))

    combined = dict(
        d3_estimation_floor_pct=D3_FLOOR_PCT,
        fixtures=sorted(by_fixture),
        by_fixture={tag: d["summary"] for tag, d in by_fixture.items()},
        by_fixture_full=by_fixture,
        paired_vs_unpaired=rows,
        # dk = 2*pi/L_solve = k_lin/p depends ONLY on p, so the band's bin COUNT is
        # invariant across every n tested. Read straight off the rows rather than asserted.
        n_band_bins_by_grid={
            n: sorted({row["n_band_bins"] for d in by_fixture.values()
                       for row in d["by_grid"][n]["rows"]})
            for n in ("96", "128", "256", "512")},
        task11_interp_error_summary=unpaired["task11_interp_error_summary"],
        note=("PAIRED sweep: for each (fixture, seed) ONE 512^2 initial condition is drawn "
              "exactly as eval.rollout.simulate draws it, spectrally decimated per species "
              "to each coarse n, and every grid rolled out from its own band-limited copy "
              "of that SAME physical IC. This is the grid-fidelity headline. The unpaired "
              "sweep in raps_fidelity.json compares grids across UNRELATED IC "
              "realisations (simulate draws standard_normal((N, n, n)), so seed-s@96 and "
              "seed-s@512 share nothing physical) and is retained, reframed, as evidence "
              "of nonlinear PATTERN-SELECTION variance — a real measurement of a different "
              "quantity. The n-decision is HELD FOR THE OWNER; nothing here rules it."),
    )
    out_path = os.path.join(OUT_DIR, "raps_fidelity_paired.json")
    with open(out_path, "w") as fh:
        json.dump(combined, fh, indent=2)

    print(f"D3 floor: ~{D3_FLOOR_PCT:.0f}%/bin   (paired | unpaired, %/bin)")
    for row in rows:
        print(f"[{row['tag']:16s}] n={row['n']:4d}  paired mean={row['paired_mean']:6.2f}% "
              f"max={row['paired_max']:6.2f}%  | unpaired mean={row['unpaired_mean']:6.2f}% "
              f"max={row['unpaired_max']:6.2f}%  clears={row['paired_clears_floor_all_seeds']}")
    print(f"band bins per grid: {combined['n_band_bins_by_grid']}")
    print(f"wrote {out_path}")
    return 0


# ------------------------------------------------------------------ fixture enumeration

#: Two Turing-unstable fixtures whose `k_lin` agree to within this relative tolerance are
#: treated as near-duplicate dynamics for fixture-selection purposes. UNCALIBRATED — it is
#: a fixture-selection convenience, not a scientific threshold, and no reported number is
#: judged against it; the enumeration artifact lists every candidate and its k_lin so the
#: selection can be re-derived under any other tolerance.
NEAR_DUPLICATE_REL_TOL = 0.01

ENUM_PATH = os.path.join(OUT_DIR, "fixture_enumeration.json")


def enumerate_checkpoints() -> dict:
    """Enumerate EVERY tracked `checkpoints/model.pt` in this repo, record whether it is
    Turing-unstable and at what `k_lin`, flag near-duplicate `k_lin` pairs, and say which
    candidates `FIXTURES` selected and why each other one was not.

    This exists because the fixture selection was previously stated only in a docstring
    ("5 of 11 tracked checkpoints Turing-unstable, one near-duplicate dropped") with
    nothing tracked behind it. Written to `results/fixture_enumeration.json`.
    """
    import subprocess
    from rngrn.losses.terms import steady_state

    out = subprocess.run(["git", "ls-files"], capture_output=True, text=True, check=True)
    paths = sorted(p for p in out.stdout.splitlines() if p.endswith("checkpoints/model.pt"))
    if not paths:
        raise RuntimeError("git ls-files found no tracked checkpoints/model.pt")

    selected_paths = {v: k for k, v in FIXTURES.items()}
    rows = []
    for path in paths:
        run_dir = os.path.basename(os.path.dirname(os.path.dirname(path)))
        rec = dict(path=path, run=run_dir, selected_as=selected_paths.get(path))
        try:
            model = load_fixture(path)
        except Exception as exc:                      # nondim path, unreadable state dict…
            rec.update(loadable=False, load_error=f"{type(exc).__name__}: {exc}",
                       turing_unstable=None)
            rows.append(rec)
            continue
        rec["loadable"] = True
        # A raw fixed-grid dispersion scan, reported for EVERY checkpoint — `linear_kstar`
        # refuses (raises) on a non-Turing model, so without this the artifact would carry
        # no number at all for the ones it rejects.
        xs, converged = steady_state(model)
        rec["steady_state_converged"] = bool(converged)
        if converged:
            J = model.jacobian(xs, create_graph=False)
            kg = torch.linspace(1e-3, 1.0, 4000, dtype=model.dtype)
            sig = model.dispersion(xs, kg, J=J).detach().numpy()
            i = int(np.argmax(sig))
            rec.update(scan_k_argmax=_j(float(kg[i])), scan_sig_max=_j(float(sig[i])),
                       scan_argmax_at_grid_floor=bool(i == 0))
        try:
            k_lin, sig_max, _ = linear_kstar(model)
            rec.update(turing_unstable=True, k_lin=_j(k_lin), sig_max_lin=_j(sig_max))
        except RuntimeError as exc:
            rec.update(turing_unstable=False, k_lin=None, sig_max_lin=None,
                       rejected_by_linear_kstar=str(exc))
        rows.append(rec)

    turing = [r for r in rows if r.get("turing_unstable")]
    near_dupes = []
    for i, a in enumerate(turing):
        for b in turing[i + 1:]:
            rel = abs(a["k_lin"] - b["k_lin"]) / (0.5 * (a["k_lin"] + b["k_lin"]))
            if rel < NEAR_DUPLICATE_REL_TOL:
                near_dupes.append(dict(a=a["run"], b=b["run"], k_lin_a=a["k_lin"],
                                       k_lin_b=b["k_lin"], rel_diff=_j(rel),
                                       a_selected=a["selected_as"] is not None,
                                       b_selected=b["selected_as"] is not None))

    dupe_runs = {r for d in near_dupes for r in (d["a"], d["b"])}
    for r in turing:
        if r["selected_as"] is not None:
            r["selection_note"] = "selected as a FIXTURES entry"
        elif r["run"] in dupe_runs:
            r["selection_note"] = (
                f"dropped: k_lin within {NEAR_DUPLICATE_REL_TOL:.0%} of another "
                "Turing-unstable checkpoint's (see near_duplicate_pairs)")
        else:
            r["selection_note"] = "not selected (see notes)"

    # Single-linkage clustering of the Turing-unstable k_lin values at the same tolerance,
    # so the artifact says how many DISTINCT fixture dynamics (by this criterion) exist
    # rather than only which pairs happen to be close.
    clusters: list[list[dict]] = []
    for r in sorted(turing, key=lambda r: r["k_lin"]):
        if clusters and abs(r["k_lin"] - clusters[-1][-1]["k_lin"]) / (
                0.5 * (r["k_lin"] + clusters[-1][-1]["k_lin"])) < NEAR_DUPLICATE_REL_TOL:
            clusters[-1].append(r)
        else:
            clusters.append([r])
    cluster_rows = [dict(k_lin_min=c[0]["k_lin"], k_lin_max=c[-1]["k_lin"],
                         members=[m["run"] for m in c],
                         selected_members=[m["run"] for m in c
                                           if m["selected_as"] is not None],
                         sig_max_lin=[m["sig_max_lin"] for m in c]) for c in clusters]
    multi_selected = [c for c in cluster_rows if len(c["selected_members"]) > 1]

    summary = dict(
        n_tracked_checkpoints=len(rows),
        n_turing_unstable=len(turing),
        n_selected=sum(1 for r in rows if r["selected_as"] is not None),
        selected=[r["run"] for r in rows if r["selected_as"] is not None],
        near_duplicate_rel_tol=NEAR_DUPLICATE_REL_TOL,
        near_duplicate_pairs=near_dupes,
        k_lin_clusters=cluster_rows,
        n_distinct_k_lin_clusters=len(cluster_rows),
        selection_caveat=(
            "MEASURED, and it corrects the story this selection used to be described by. "
            f"All {len(turing)} Turing-unstable checkpoints fall into "
            f"{len(cluster_rows)} k_lin cluster(s) at a {NEAR_DUPLICATE_REL_TOL:.0%} "
            "tolerance, and " + (
                f"{len(multi_selected)} cluster(s) contribute MORE THAN ONE selected "
                "fixture — so FIXTURES does not sample distinct k_lin. The selected "
                "fixtures do differ in sig_max_lin and in time-to-saturation (recorded "
                "here and in the sweep artifacts), so they are not redundant models; but "
                "'the more different pair was kept' is not what the k_lin numbers show."
                if multi_selected else
                "no cluster contributes more than one selected fixture.")),
        method=("`git ls-files` for checkpoints/model.pt; `diag_fft_d2.load_fixture` + "
                "`linear_kstar` (steady_state -> jacobian -> model.dispersion argmax, "
                "k-grid edge doubled until the argmax is interior) on each; a checkpoint "
                "is Turing-unstable iff linear_kstar accepts it (sig_max > 0). Generated "
                "by `r3_raps_fidelity.py --enumerate-fixtures`, not hand-written."),
    )
    doc = dict(summary=summary, checkpoints=rows)
    os.makedirs(OUT_DIR, exist_ok=True)
    with open(ENUM_PATH, "w") as fh:
        json.dump(doc, fh, indent=2)
    for r in rows:
        print(f"{r['run']:44s} turing={str(r.get('turing_unstable')):5s} "
              f"k_lin={r.get('k_lin')} sel={r.get('selected_as')}")
    print(f"{summary['n_turing_unstable']}/{summary['n_tracked_checkpoints']} "
          f"Turing-unstable; near-duplicate pairs: {near_dupes}")
    print(f"wrote {ENUM_PATH}")
    return doc


# --------------------------------------------------------------------------- aggregation

def aggregate() -> int:
    """Merge every experiments/.../raps_fidelity_<tag>.json present into the combined
    raps_fidelity.json, add Task 11's interpolation number (§4.3 pairing), and report
    whether the n-trend separates from seed noise across fixtures."""
    # `raps_fidelity_*.json` also matches the PAIRED artifacts (`raps_fidelity_paired.json`
    # and `raps_fidelity_paired_<tag>.json`), which have a different schema — exclude them
    # explicitly rather than letting the merge trip over a missing "summary" key.
    paths = sorted(p for p in glob.glob(os.path.join(OUT_DIR, "raps_fidelity_*.json"))
                   if not os.path.basename(p).startswith("raps_fidelity_paired"))
    if not paths:
        raise RuntimeError(f"no per-fixture results found under {OUT_DIR} — run with --tag "
                           "for each fixture in FIXTURES first")
    by_fixture = {}
    for p in paths:
        with open(p) as fh:
            d = json.load(fh)
        by_fixture[d["summary"]["tag"]] = d

    # Fail loud (CLAUDE.md §4): §4.3 REQUIRES Task 11's number to be folded in here, so a
    # missing file is a broken pairing, not an optional extra. An `if os.path.exists(...)`
    # guard used to leave `task11_interp_error_summary: null` in the tracked artifact.
    if not os.path.exists(TASK11_INTERP_JSON):
        raise FileNotFoundError(
            f"{TASK11_INTERP_JSON} not found — spec §4.3 pairs the RAPS band fidelity with "
            "Task 11's target-interpolation error; run Task 11's driver first rather than "
            "emitting a null in its place")
    with open(TASK11_INTERP_JSON) as fh:
        task11 = json.load(fh)["summary"]

    # ---- does the n-trend separate from seed noise? For each fixture, is mean(96) >
    # mean(128) > mean(256) (monotonic improvement)? And does the 95%-ish spread (max-min
    # across seeds) at a fixed n dwarf the mean DIFFERENCE between grids?
    trend_rows = []
    for tag, d in by_fixture.items():
        pg = d["summary"]["per_grid"]
        means = {n: pg[n]["per_bin_pct_mean"] for n in ("96", "128", "256")}
        spreads = {n: pg[n]["per_bin_pct_max"] - by_fixture[tag]["by_grid"][n]
                  ["per_bin_pct_min"] for n in ("96", "128", "256")}
        monotonic = means["96"] > means["128"] > means["256"]
        gaps = [means["96"] - means["128"], means["128"] - means["256"]]
        # `all`, not `any`: the reported claim is that the per-grid seed spread dwarfs
        # EVERY grid-to-grid mean gap. It happens to hold on this data under either
        # quantifier, but `any` would not have licensed the sentence that was written.
        noise_dominates = all(abs(g) < spreads[n] for g, n in
                              zip(gaps, ("96", "128")))
        trend_rows.append(dict(tag=tag, k_lin=d["summary"]["k_lin"], means=means,
                               spreads=spreads, monotonic_96_128_256=monotonic,
                               grid_gaps=gaps, seed_noise_dominates_grid_gap=noise_dominates,
                               coarsest_grid_clearing_floor=
                                   d["summary"]["coarsest_grid_clearing_floor"],
                               n_seeds=len(d["summary"]["seeds"])))

    combined = dict(
        d3_estimation_floor_pct=D3_FLOOR_PCT,
        fixtures=list(by_fixture.keys()),
        by_fixture={tag: d["summary"] for tag, d in by_fixture.items()},
        by_fixture_full={tag: d for tag, d in by_fixture.items()},
        cross_fixture_trend=trend_rows,
        task11_interp_error_summary=task11,
        note=("Multi-fixture sweep (controller-requested, held for more evidence after the "
              "1-fixture/3-seed run could not separate a genuine n-trend from seed noise). "
              "See cross_fixture_trend per fixture for whether the 96/128/256 means are "
              "monotonically decreasing and whether the per-grid seed spread dwarfs the "
              "grid-to-grid mean gap."),
    )
    out_path = os.path.join(OUT_DIR, "raps_fidelity.json")
    with open(out_path, "w") as fh:
        json.dump(combined, fh, indent=2)

    print(f"D3 floor: ~{D3_FLOOR_PCT:.0f}%/bin")
    for row in trend_rows:
        print(f"[{row['tag']}] k_lin={row['k_lin']:.4f} n_seeds={row['n_seeds']}  "
              f"means: 96={row['means']['96']:.2f}% 128={row['means']['128']:.2f}% "
              f"256={row['means']['256']:.2f}%  monotonic={row['monotonic_96_128_256']}  "
              f"coarsest_clearing={row['coarsest_grid_clearing_floor']}  "
              f"seed_noise_dominates={row['seed_noise_dominates_grid_gap']}")
    print(f"wrote {out_path}")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--tag", choices=sorted(FIXTURES), default=None,
                    help="fixture tag to run (see FIXTURES); omit with --aggregate")
    ap.add_argument("--seeds", default="0,1,2",
                    help="comma-separated seed list, e.g. 0,1,2,3,4,5,6,7")
    ap.add_argument("--aggregate", action="store_true",
                    help="merge all raps_fidelity_<tag>.json into raps_fidelity.json")
    ap.add_argument("--paired", action="store_true",
                    help="PAIRED grid-fidelity measurement (the headline): coarse grids "
                         "start from the 512^2 IC decimated, not from an unrelated draw")
    ap.add_argument("--aggregate-paired", action="store_true",
                    help="merge all raps_fidelity_paired_<tag>.json into "
                         "raps_fidelity_paired.json")
    ap.add_argument("--enumerate-fixtures", action="store_true",
                    help="write results/fixture_enumeration.json (no rollouts)")
    args = ap.parse_args()

    if args.enumerate_fixtures:
        enumerate_checkpoints()
        return 0
    if args.aggregate_paired:
        return aggregate_paired()
    if args.aggregate:
        return aggregate()
    if args.tag is None:
        raise SystemExit("pass --tag <fixture> or --aggregate")
    seeds = tuple(int(s) for s in args.seeds.split(","))
    if args.paired:
        run_fixture_paired(FIXTURES[args.tag], args.tag, seeds)
    else:
        run_fixture(FIXTURES[args.tag], args.tag, seeds)
    return 0


if __name__ == "__main__":
    sys.exit(main())
