"""overparam.py — over-parameterisation metrics for EXPERIMENT B (SCAFFOLD).

STATUS: SCAFFOLD. This module is a scoring harness, not a validated scientific
instrument. The metrics below are defined and unit-tested on synthetic matrices
(tests/test_overparam_scoring.py); their thresholds are NOT calibrated against any
recovery run, and no claim is made here that the recovery pipeline passes them.

THE EXPERIMENT
--------------
Experiment B feeds the pipeline a Turing frame generated by a TWO-species system
but runs recovery with a model of N=3 species (deliberate over-parameterisation).
Both true channels are observed; the third model species is a spare slot for which
no ground truth exists.

There is therefore NO correct 3x3 answer, and a whole-matrix score (e.g. a 3x3
sign-agreement fraction against a 2x2 truth) is not merely noisy — it is undefined.
Success has two independent halves:

  (i)  INERTNESS  — the spare species must not couple to the real system. A
       confidently-wired third gene is a FALSE POSITIVE: precisely the failure mode
       this experiment exists to detect.
  (ii) FIDELITY   — the observed 2x2 sub-block of the recovered Jacobian must
       reproduce the true 2x2 Jacobian.

`spurious_species_metrics` scores (i), `observed_block_agreement` scores (ii), and
`overparam_report` is a convenience wrapper returning one flat row for the run index.

FIREWALL
--------
SCORING SIDE. This module reads AnswerKey quantities (`answer_key.J`,
`answer_key.n_species_true`) and must never be imported by a recovery-side module.
It imports numpy at module scope and torch only inside `overparam_report` (the one
function that needs a live model), so the two pure-matrix metrics are usable without
torch.

INDEX ALIGNMENT (why the observed block needs no permutation alignment)
----------------------------------------------------------------------
Model species indices are arbitrary in general. For the OBSERVED channels they are
not: `data.gate._observe` takes truth channels `observed_idx` in that order, and
`losses.terms.stationarity_residual` writes observed frame row `r` into model index
`observed_idx[r]`. So model index i is pinned to truth channel i for every
i in observed_idx, and the observed sub-block can be compared entry-by-entry.
Permutation ambiguity survives only among the UNOBSERVED model indices, which is why
`spurious_species_metrics` refuses the ambiguous case (see its docstring).

CONVENTION
----------
J[i, j] = d f_i / d x_j: row i is the TARGET, column j is the REGULATOR. Hence
"coupling INTO the spare species e" reads off row e, and "coupling OUT OF e" reads
off column e.
"""
from __future__ import annotations

from typing import Any, Iterable, Sequence

import numpy as np

__all__ = [
    "spurious_species_metrics",
    "observed_block_agreement",
    "overparam_report",
    "DEFAULT_COUPLING_THRESHOLD",
    "DEFAULT_SIGN_ZERO_TOL",
]

#: Default coupling threshold for `spurious_species_metrics`, interpreted in
#: `threshold_mode="relative"` as a fraction of the largest |J| entry in the observed
#: sub-block. STARTING POINT ONLY — see the `coupling_threshold` docstring section.
DEFAULT_COUPLING_THRESHOLD: float = 0.05

#: Default relative dead-zone below which a Jacobian entry is treated as sign-zero.
#: Matches the convention already used in validate._sign_structure.
DEFAULT_SIGN_ZERO_TOL: float = 1e-9


# ======================================================================================
# internal helpers (module-private; fail loud, no silent coercion)
# ======================================================================================
def _as_square(J: Any, name: str) -> np.ndarray:
    """Return J as a finite float 2-D square array, or raise."""
    arr = np.asarray(J, dtype=float)
    if arr.ndim != 2 or arr.shape[0] != arr.shape[1]:
        raise ValueError(f"{name} must be a square 2-D matrix; got shape {arr.shape}.")
    if arr.size == 0:
        raise ValueError(f"{name} is empty.")
    if not np.all(np.isfinite(arr)):
        raise ValueError(
            f"{name} contains non-finite entries (nan/inf); refusing to score it. "
            "A non-finite Jacobian means the recovery or the steady state diverged.")
    return arr


def _as_index_tuple(observed_idx: Iterable[int], n_model: int) -> tuple[int, ...]:
    """Validate observed_idx against a model of n_model species."""
    idx = tuple(int(i) for i in observed_idx)
    if len(idx) == 0:
        raise ValueError("observed_idx is empty: nothing was observed, nothing to score.")
    if len(set(idx)) != len(idx):
        raise ValueError(f"observed_idx contains duplicates: {idx}.")
    # a channel mapped outside the model's species range is a wiring bug
    bad = [i for i in idx if i < 0 or i >= n_model]
    if bad:
        raise ValueError(
            f"observed_idx {idx} contains indices outside range(0, {n_model}) "
            f"for the recovered model: {bad}.")
    return idx


def _sign_structure(J: np.ndarray, sign_zero_tol: float) -> np.ndarray:
    """Sign pattern of J with a magnitude-relative dead-zone.

    Entries with |J_ij| <= sign_zero_tol * max|J| are mapped to 0 rather than to
    +-1, so numerically-negligible entries do not count as edges. Same convention as
    validate._sign_structure (kept local so this module stands alone).
    """
    if not np.isfinite(sign_zero_tol) or sign_zero_tol < 0:
        raise ValueError(f"sign_zero_tol must be finite and >= 0; got {sign_zero_tol}.")
    scale = float(np.abs(J).max())
    dead = sign_zero_tol * scale
    return np.sign(np.where(np.abs(J) > dead, J, 0.0))


# ======================================================================================
# 1. inertness of the spare species
# ======================================================================================
def spurious_species_metrics(
    J_rec: Any,
    D_rec: Any,
    observed_idx: Iterable[int],
    n_true: int,
    coupling_threshold: float = DEFAULT_COUPLING_THRESHOLD,
    threshold_mode: str = "relative",
) -> dict:
    """Quantify whether the model's SPARE species are inert (Experiment B, half (i)).

    Parameters
    ----------
    J_rec : (N, N) array_like
        Recovered Jacobian, J[i, j] = d f_i / d x_j, evaluated at the recovered x*.
        Must be square and finite (raises otherwise).
    D_rec : (N,) array_like
        Recovered diffusion coefficients. Used for DIAGNOSTIC fields only (see below);
        it does not enter any pass/fail criterion.
    observed_idx : sequence of int
        Model indices that were pinned to observed channels (see INDEX ALIGNMENT in
        the module docstring). These indices are never candidates for spuriousness:
        they carry real data.
    n_true : int
        Number of species in the ground-truth system, from AnswerKey.n_species_true.
        Read from the answer key, so this function is SCORING SIDE.
    coupling_threshold : float, default DEFAULT_COUPLING_THRESHOLD (0.05)
        The inertness cut. NOT a calibrated constant — a starting point for the user
        to tune once real recovery runs exist. In ``threshold_mode="relative"`` it is
        a fraction of ``coupling_scale`` (the largest |J| entry of the observed
        sub-block), i.e. the default reads "a spurious edge counts as absent if it is
        weaker than 5% of the strongest edge in the recovered real system". A relative
        cut is the default because the recovered Jacobian's overall magnitude is not
        pinned by anything in the objective, so an absolute cut in units of 1/time
        would silently change meaning between runs. In ``"absolute"`` mode the value
        is compared to |J| entries directly. The realised cut is always returned as
        ``coupling_threshold_used`` so a run row records what was actually applied.
    threshold_mode : {"relative", "absolute"}
        How to interpret ``coupling_threshold``. Unknown values raise.

    Returns
    -------
    dict of flat scalars/bools/strings (safe for a sqlite/jsonl run index):
        n_model, n_true, n_observed, n_extra          : ints
        extra_idx                                     : str, e.g. "(2,)" — the model
            indices beyond the true species count, i.e. the spurious-species
            candidates. In Experiment B these are exactly the UNOBSERVED indices.
        overparameterised                             : bool (n_model > n_true)
        extra_norm_frac                               : ||J_E||_F / ||J||_F, where J_E
            is J masked to the UNION of the extra species' rows and columns. The union
            (not row-sum + column-sum) is used so the extra-extra block, diagonal
            included, is counted exactly once.
        extra_energy_frac                             : the same quantity squared,
            i.e. the additive share of sum(J^2). Reported because the squared form is
            the one that partitions.
        max_abs_coupling_to_extra                     : max |J[e, j]| over e in extra,
            j a NON-extra index — the single strongest edge INTO a spare species.
            A max, not a mean: one strong spurious edge is the failure mode, and a
            mean over a mostly-empty row hides it.
        max_abs_coupling_from_extra                   : max |J[i, e]| over i non-extra,
            e in extra — the strongest edge OUT OF a spare species.
        rel_coupling_to_extra, rel_coupling_from_extra: the same two, divided by
            coupling_scale (nan in absolute mode, where no scale is formed).
        max_abs_coupling_within_extra                 : strongest off-diagonal edge
            BETWEEN two spare species (nan when n_extra < 2). Excluded from the
            criterion: spare-spare wiring is invisible to the real system.
        max_abs_diag_extra                            : max |J[e, e]|. Excluded from
            the criterion by design — a spare species may legitimately retain its own
            decay term while being dynamically disconnected.
        coupling_scale, coupling_threshold_arg, coupling_threshold_used,
        coupling_threshold_mode                       : threshold provenance.
        D_extra_max, D_observed_max                   : diagnostic only. If the spare
            species is decoupled its diffusion cannot influence the observed
            dynamics, so D is reported for transparency, not scored.
        decoupled                                     : bool — both
            max_abs_coupling_to_extra and max_abs_coupling_from_extra are strictly
            below coupling_threshold_used.
        spare_species_inert                           : bool — THE HEADLINE PASS/FAIL.
            Currently identical to ``decoupled``: the criterion is exactly "no
            above-threshold edge in either direction between a spare species and the
            real system". True = the spare capacity stayed unused (the desired
            outcome). False = the recovery wired a confident third gene that does not
            exist = FALSE POSITIVE. Scope, stated honestly: this is a Jacobian-only
            criterion evaluated at a single recovered x*. It does NOT test that the
            inferred latent field for the spare species is featureless, nor anything
            about the spare species away from x*. `overparam_report` returns latent
            spatial-contrast diagnostics alongside it, but deliberately does not fold
            them into this boolean.

    Undefined-by-construction case
    ------------------------------
    When n_model == n_true there is no spare species and the question is vacuous.
    The function returns n_extra=0, extra_idx="()", overparameterised=False, all
    coupling/fraction fields nan, and ``decoupled = spare_species_inert = None``
    (SQL NULL / JSON null) — an explicit "criterion undefined", never a fabricated
    pass.

    Raises
    ------
    ValueError
        On a non-square/non-finite J_rec, a D_rec of the wrong length, an invalid
        observed_idx, n_true < 1, n_model < n_true (the model cannot even represent
        the truth — this metric would be meaningless), or an unknown threshold_mode.
    NotImplementedError
        When the spare species' IDENTITY is ambiguous: n_extra > 0 but the model has
        more unobserved slots than spare species (e.g. n_true=3, n_model=4, m=2). Then
        which unobserved slot is the spurious one is not determined without a
        permutation alignment, and this module refuses to guess. Experiment B's
        geometry (every unobserved slot is spare) is the supported case.
    """
    J = _as_square(J_rec, "J_rec")
    n_model = int(J.shape[0])
    D = np.asarray(D_rec, dtype=float).reshape(-1)
    if D.shape[0] != n_model:
        raise ValueError(
            f"D_rec has {D.shape[0]} entries but J_rec is {n_model}x{n_model}.")
    if not np.all(np.isfinite(D)):
        raise ValueError("D_rec contains non-finite entries; refusing to score it.")
    obs = _as_index_tuple(observed_idx, n_model)
    n_true = int(n_true)
    if n_true < 1:
        raise ValueError(f"n_true must be >= 1; got {n_true}.")
    if n_model < n_true:
        raise ValueError(
            f"recovered model has N={n_model} species but the truth has {n_true}: the "
            "model cannot represent the true system, so spare-species metrics are "
            "meaningless. This is an under-parameterised run, not Experiment B.")
    if threshold_mode not in ("relative", "absolute"):
        raise ValueError(
            f"threshold_mode must be 'relative' or 'absolute'; got {threshold_mode!r}.")
    if not np.isfinite(coupling_threshold) or coupling_threshold < 0:
        raise ValueError(
            f"coupling_threshold must be finite and >= 0; got {coupling_threshold}.")

    unobserved = tuple(i for i in range(n_model) if i not in obs)
    n_extra = n_model - n_true
    if n_extra > len(unobserved):
        raise ValueError(
            f"model N={n_model}, truth n_true={n_true}, observed={obs}: that implies "
            f"{n_extra} spare species but only {len(unobserved)} unobserved slots, so an "
            "OBSERVED channel would have to be spurious. That contradicts the "
            "observed-index alignment this module relies on — check observed_idx/n_true.")
    if n_extra > 0 and len(unobserved) > n_extra:
        raise NotImplementedError(
            f"spare-species identity is ambiguous: model N={n_model}, truth n_true="
            f"{n_true}, unobserved slots {unobserved} but only {n_extra} of them are "
            "spare. Which unobserved index is the spurious one is not determined "
            "without a permutation alignment between model and truth species, and this "
            "module will not guess. Supported case (Experiment B): every unobserved "
            "slot is spare.")

    # Guarded above: when n_extra > 0 the ambiguous case has already raised, so every
    # unobserved slot is spare and `extra` is exactly `unobserved`.
    extra = unobserved if n_extra > 0 else ()

    nan = float("nan")
    out: dict = dict(
        n_model=n_model,
        n_true=n_true,
        n_observed=len(obs),
        n_extra=int(n_extra),
        extra_idx=repr(extra),
        overparameterised=bool(n_extra > 0),
        coupling_threshold_arg=float(coupling_threshold),
        coupling_threshold_mode=str(threshold_mode),
        D_observed_max=float(np.abs(D[list(obs)]).max()),
    )

    if n_extra == 0:
        # No spare species exists: the inertness question is undefined, not passed.
        out.update(
            extra_norm_frac=nan, extra_energy_frac=nan,
            max_abs_coupling_to_extra=nan, max_abs_coupling_from_extra=nan,
            rel_coupling_to_extra=nan, rel_coupling_from_extra=nan,
            max_abs_coupling_within_extra=nan, max_abs_diag_extra=nan,
            coupling_scale=nan, coupling_threshold_used=nan,
            D_extra_max=nan, decoupled=None, spare_species_inert=None,
        )
        return out

    non_extra = tuple(i for i in range(n_model) if i not in extra)

    # --- norm share carried by the extra rows+columns (union mask: no double count) ---
    fro_all = float(np.sqrt((J ** 2).sum()))
    if fro_all <= 0.0:
        raise ValueError(
            "||J_rec||_F is zero: the recovered Jacobian is identically zero, which is "
            "not a recovery. Refusing to report a norm fraction of nothing.")
    mask = np.zeros_like(J, dtype=bool)
    mask[list(extra), :] = True
    mask[:, list(extra)] = True
    fro_extra = float(np.sqrt((J[mask] ** 2).sum()))
    out["extra_norm_frac"] = fro_extra / fro_all
    out["extra_energy_frac"] = (fro_extra / fro_all) ** 2

    # --- strongest single edge into / out of the spare species ------------------------
    ei, ni = list(extra), list(non_extra)
    to_block = np.abs(J[np.ix_(ei, ni)])      # rows = spare targets, cols = real regulators
    from_block = np.abs(J[np.ix_(ni, ei)])    # rows = real targets, cols = spare regulators
    max_to = float(to_block.max())
    max_from = float(from_block.max())
    out["max_abs_coupling_to_extra"] = max_to
    out["max_abs_coupling_from_extra"] = max_from
    out["max_abs_diag_extra"] = float(np.abs(np.diag(J)[ei]).max())
    if n_extra >= 2:
        sub = np.abs(J[np.ix_(ei, ei)]).copy()
        np.fill_diagonal(sub, 0.0)
        out["max_abs_coupling_within_extra"] = float(sub.max())
    else:
        out["max_abs_coupling_within_extra"] = nan
    out["D_extra_max"] = float(np.abs(D[ei]).max())

    # --- threshold ---------------------------------------------------------------------
    obs_block = J[np.ix_(list(obs), list(obs))]
    scale = float(np.abs(obs_block).max())
    if threshold_mode == "relative":
        if not np.isfinite(scale) or scale <= 0.0:
            raise ValueError(
                "cannot form a relative coupling threshold: the observed sub-block of "
                "J_rec is identically zero, so there is no recovered real system to "
                "scale against. Pass threshold_mode='absolute' with an explicit cut.")
        thr = coupling_threshold * scale
        out["coupling_scale"] = scale
        out["rel_coupling_to_extra"] = max_to / scale
        out["rel_coupling_from_extra"] = max_from / scale
    else:
        thr = float(coupling_threshold)
        out["coupling_scale"] = scale
        out["rel_coupling_to_extra"] = nan
        out["rel_coupling_from_extra"] = nan
    out["coupling_threshold_used"] = float(thr)

    decoupled = bool(max_to < thr and max_from < thr)
    out["decoupled"] = decoupled
    out["spare_species_inert"] = decoupled
    return out


# ======================================================================================
# 2. fidelity on the observed sub-block
# ======================================================================================
def observed_block_agreement(
    J_rec: Any,
    J_true: Any,
    observed_idx: Iterable[int],
    sign_zero_tol: float = DEFAULT_SIGN_ZERO_TOL,
) -> dict:
    """Compare the OBSERVED sub-block of J_rec against the truth (half (ii)).

    This is the "did it get the REAL system right" half of Experiment B, and it is the
    only entry-by-entry Jacobian comparison that is well posed under
    over-parameterisation: the observed model indices are pinned to truth channels by
    the loss (see INDEX ALIGNMENT in the module docstring), so no permutation
    alignment is needed here. Rows/columns belonging to unobserved or spare species are
    excluded entirely — they have no counterpart in J_true.

    Parameters
    ----------
    J_rec : (N, N) array_like
        Recovered Jacobian at the recovered x*.
    J_true : (n_true, n_true) array_like
        Ground-truth Jacobian from AnswerKey.J. SCORING SIDE.
    observed_idx : sequence of int
        Indices that are simultaneously model indices and truth channel indices. Every
        entry must be a valid index into BOTH matrices, else this raises.
    sign_zero_tol : float, default DEFAULT_SIGN_ZERO_TOL (1e-9)
        Relative dead-zone for the sign comparison, applied independently to each
        sub-block via `_sign_structure` (an entry below sign_zero_tol * max|block| is
        called sign-zero rather than +-1). At the 1e-9 default this excludes only
        numerically-negligible entries; raise it if you want weak edges treated as
        absent.

    Returns
    -------
    dict of flat scalars/strings:
        n_observed                  : int, size of the compared sub-block
        observed_idx                : str
        obs_sign_match_frac         : fraction of the n_observed**2 entries whose
            sign structures agree (diagonal included)
        obs_sign_match_offdiag_frac : the same over off-diagonal entries only, which is
            where the interaction topology lives (nan when n_observed == 1)
        obs_rel_fro_err             : ||J_rec_sub - J_true_sub||_F / ||J_true_sub||_F.
            Scale-SENSITIVE: it charges for overall magnitude mismatch as well as
            structural error, and nothing in the recovery objective pins the overall
            magnitude of J.
        obs_scale_ratio             : the scalar c minimising ||c*J_rec_sub -
            J_true_sub||_F, i.e. the best-fit magnitude ratio (c = <rec,true>/||rec||^2)
        obs_rel_fro_err_scaled      : the same relative error after applying that best
            scalar — the scale-free structural error. Report both; a large gap between
            them means "right shape, wrong magnitude".
        obs_fro_rec, obs_fro_true   : the two sub-block Frobenius norms

    Raises
    ------
    ValueError
        On non-square/non-finite inputs, an observed index out of range for either
        matrix, or ||J_true_sub||_F == 0 (no truth signal to divide by — reporting 0.0
        or nan silently would hide that the answer key is empty).
    """
    R = _as_square(J_rec, "J_rec")
    T = _as_square(J_true, "J_true")
    obs = _as_index_tuple(observed_idx, R.shape[0])
    bad = [i for i in obs if i >= T.shape[0]]
    if bad:
        raise ValueError(
            f"observed_idx {obs} indexes outside the true Jacobian (shape {T.shape}): "
            f"{bad}. An observed channel with no truth counterpart cannot be scored — "
            "check n_true / observed_idx.")
    ix = list(obs)
    Rs = R[np.ix_(ix, ix)]
    Ts = T[np.ix_(ix, ix)]
    m = len(ix)

    fro_true = float(np.sqrt((Ts ** 2).sum()))
    fro_rec = float(np.sqrt((Rs ** 2).sum()))
    if fro_true <= 0.0:
        raise ValueError(
            "the observed sub-block of J_true is identically zero: there is no truth "
            "signal to compare against, so a relative error is undefined.")

    s_rec = _sign_structure(Rs, sign_zero_tol)
    s_true = _sign_structure(Ts, sign_zero_tol)
    agree = (s_rec == s_true)
    off = ~np.eye(m, dtype=bool)

    denom_rec = float((Rs ** 2).sum())
    if denom_rec > 0.0:
        c = float((Rs * Ts).sum() / denom_rec)
        rel_scaled = float(np.sqrt(((c * Rs - Ts) ** 2).sum()) / fro_true)
    else:
        # Rs identically zero: no scalar rescaling can help, and c is undefined.
        c = float("nan")
        rel_scaled = float("nan")

    return dict(
        n_observed=m,
        observed_idx=repr(obs),
        obs_sign_match_frac=float(agree.mean()),
        obs_sign_match_offdiag_frac=(float(agree[off].mean()) if m > 1 else float("nan")),
        obs_rel_fro_err=float(np.sqrt(((Rs - Ts) ** 2).sum()) / fro_true),
        obs_scale_ratio=c,
        obs_rel_fro_err_scaled=rel_scaled,
        obs_fro_rec=fro_rec,
        obs_fro_true=fro_true,
        obs_sign_zero_tol=float(sign_zero_tol),
    )


# ======================================================================================
# 3. run-index wrapper
# ======================================================================================
def _latent_diagnostics(latent_fields: Any, observed_idx: Sequence[int],
                        extra_idx: Sequence[int], n_model: int) -> dict:
    """Spatial-contrast diagnostics for the spare species' inferred latent field.

    DIAGNOSTIC ONLY — deliberately not folded into `spare_species_inert`, because a
    contrast cut has not been calibrated. `latent_fields` rows map to the unobserved
    model indices in ascending order (the convention in losses.terms.stationarity_
    residual and recover.recover). Returns nan fields with a stated reason when no
    latent field was inferred (m == N) rather than inventing a value.
    """
    nan = float("nan")
    if latent_fields is None:
        return dict(latent_extra_std_max=nan, latent_extra_absmean_max=nan,
                    latent_extra_rel_contrast=nan,
                    latent_status="absent: no latent fields (m == N or not returned)")
    lat = np.asarray(latent_fields, dtype=float)
    lat_idx = [i for i in range(n_model) if i not in tuple(observed_idx)]
    if lat.ndim != 3 or lat.shape[0] != len(lat_idx):
        raise ValueError(
            f"latent_fields has shape {lat.shape}, expected ({len(lat_idx)}, H, W) for "
            f"unobserved model indices {lat_idx}.")
    rows = [lat_idx.index(e) for e in extra_idx]
    if not rows:
        return dict(latent_extra_std_max=nan, latent_extra_absmean_max=nan,
                    latent_extra_rel_contrast=nan,
                    latent_status="not applicable: no spare species")
    block = lat[rows]
    std = float(np.max([float(np.std(block[r])) for r in range(block.shape[0])]))
    absmean = float(np.max([abs(float(np.mean(block[r]))) for r in range(block.shape[0])]))
    rel = std / absmean if absmean > 0.0 else nan
    return dict(latent_extra_std_max=std, latent_extra_absmean_max=absmean,
                latent_extra_rel_contrast=rel,
                latent_status=("ok" if absmean > 0.0 else
                               "rel_contrast undefined: latent field mean is zero"))


def overparam_report(
    result: Any,
    answer_key: Any,
    observed_idx: Iterable[int],
    coupling_threshold: float = DEFAULT_COUPLING_THRESHOLD,
    threshold_mode: str = "relative",
    sign_zero_tol: float = DEFAULT_SIGN_ZERO_TOL,
    require_true_J: bool = True,
) -> dict:
    """One flat metric row for an over-parameterised run (Experiment B). SCAFFOLD.

    Convenience wrapper: derives J_rec / D_rec from the RecoveryResult exactly as
    validate.score_recovery does (``result.model.jacobian(torch.as_tensor(
    result.xstar), create_graph=False)`` and ``result.model.D``), reads n_true and J
    from the AnswerKey, and merges `spurious_species_metrics`,
    `observed_block_agreement`, and latent diagnostics into ONE flat dict.

    All values are scalars, bools, None, or strings — no nested dicts — so a row can go
    straight into the sqlite/jsonl run index. Both ``n_true`` and ``n_model`` are always
    present so a downstream table can never silently compare an N=2-truth run against
    an N=3-truth run.

    torch is imported inside this function, not at module scope, so the two pure-matrix
    metric functions above remain importable without torch. NOTE for bare scripts: this
    sandbox needs KMP_AFFINITY=disabled and OMP_NUM_THREADS=1 exported BEFORE the first
    torch import (tests/conftest.py does it for pytest).

    Parameters
    ----------
    result : RecoveryResult
        Needs ``.model`` (with ``.jacobian`` and ``.D``), ``.xstar``, and optionally
        ``.latent_fields``.
    answer_key : AnswerKey
        Needs ``.n_species_true`` and ``.J``. SCORING SIDE — see module docstring.
    observed_idx : sequence of int
        As for the two functions above.
    coupling_threshold, threshold_mode
        Forwarded to `spurious_species_metrics`; the default 0.05 relative cut is an
        UNCALIBRATED starting point, and the realised cut is echoed in the row.
    sign_zero_tol
        Forwarded to `observed_block_agreement`.
    require_true_J : bool, default True
        With True (fail loud), a missing or mis-shaped ``answer_key.J`` raises. With
        False, the observed-block fields are omitted and ``block_status`` records why —
        use it only for datasets that genuinely ship no Jacobian.

    Returns
    -------
    dict
        Keys from `spurious_species_metrics`, plus `observed_block_agreement` keys
        (when scored), plus latent_* diagnostics, plus:
        overparam_status : str, a human-readable one-liner
        block_status     : str, "scored" or the reason it was skipped
        n_model_from_result : int, N read off the recovered model
        loss             : float, result.loss (carried through for the index)

    Raises
    ------
    ValueError
        On a missing/mis-shaped answer key (when require_true_J), an
        ``answer_key.J`` whose size disagrees with ``answer_key.n_species_true`` (the
        exact mismatch that must never be silently NaN'd), or anything the two metric
        functions reject.
    AttributeError
        If ``result`` or ``answer_key`` lacks a required field — a caller wiring bug
        that should surface, not be defaulted away.
    """
    import torch  # local import: keeps the pure-matrix metrics torch-free

    for attr in ("model", "xstar"):
        if not hasattr(result, attr):
            raise AttributeError(f"result has no '{attr}': not a RecoveryResult.")
    if not hasattr(answer_key, "n_species_true"):
        raise AttributeError("answer_key has no 'n_species_true': not an AnswerKey.")

    J_rec = result.model.jacobian(
        torch.as_tensor(np.asarray(result.xstar, dtype=float)),
        create_graph=False).detach().numpy()
    D_rec = result.model.D.detach().numpy()
    n_model = int(np.asarray(J_rec).shape[0])
    n_true = int(answer_key.n_species_true)
    obs = _as_index_tuple(observed_idx, n_model)

    row = spurious_species_metrics(
        J_rec, D_rec, obs, n_true,
        coupling_threshold=coupling_threshold, threshold_mode=threshold_mode)
    row["n_model_from_result"] = n_model
    row["overparam_status"] = (
        f"over-parameterised: model N={n_model} vs truth n_true={n_true} "
        f"({row['n_extra']} spare)" if n_model > n_true else
        f"exactly parameterised: model N={n_model} == truth n_true={n_true}; "
        "spare-species criterion undefined")

    J_true = getattr(answer_key, "J", None)
    if J_true is None:
        if require_true_J:
            raise ValueError(
                "answer_key.J is None: the observed-block half of Experiment B cannot "
                "be scored without a true Jacobian. Pass require_true_J=False to record "
                "the row without it.")
        row["block_status"] = "skipped: answer_key.J is None"
    else:
        T = np.asarray(J_true, dtype=float)
        if T.ndim != 2 or T.shape[0] != T.shape[1] or T.shape[0] != n_true:
            raise ValueError(
                f"answer_key.J has shape {T.shape} but answer_key.n_species_true="
                f"{n_true}: the answer key is internally inconsistent. Refusing to "
                "score (this is the mismatch that must never become a silent NaN).")
        row.update(observed_block_agreement(J_rec, T, obs, sign_zero_tol=sign_zero_tol))
        row["block_status"] = "scored"

    # Same identification as spurious_species_metrics: with n_extra > 0 validated there,
    # the spare indices are exactly the unobserved ones.
    unobserved = tuple(i for i in range(n_model) if i not in obs)
    extra_idx = unobserved if row["n_extra"] else ()
    row.update(_latent_diagnostics(getattr(result, "latent_fields", None), obs,
                                   extra_idx, n_model))
    row["loss"] = float(result.loss) if hasattr(result, "loss") else float("nan")

    bad = {k: v for k, v in row.items()
           if not isinstance(v, (int, float, bool, str, type(None)))}
    if bad:
        raise ValueError(
            f"overparam_report produced non-flat values for keys {sorted(bad)}; the run "
            "index accepts only scalars/bools/strings.")
    return row
